### ISSUE TITLE
Moving from kvdo 6.2.3.114 to 6.1.3.23

### ISSUE THREAD

**Issue by genxlee** [dm-vdo/kvdo#36]
I would like move from CentOS 8 to 7
After starting vdo service at CentOS 7 with configuration that was running under CentOS 8 I am getting following errors:

```
systemd[1]: Starting VDO volume services...
vdo[20804]: ERROR - 'instancemethod' object has no attribute '__getitem__'
vdo[20804]: vdo: ERROR - 'instancemethod' object has no attribute '__getitem__'
systemd[1]: vdo.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Failed to start VDO volume services.
systemd[1]: Unit vdo.service entered failed state.
systemd[1]: vdo.service failed.
```

Running `vdodumpconfig` results in:
```
vdodumpconfig: allocateVDO failed for '/dev/md254' with VDO Status: Unsupported component version
vdodumpconfig: Could not load VDO from '/dev/md254'
```

Is it somehow possible to get VDO volume up and running while moving from CentOS 8 (kmod-kvdo 6.2.3.114) to CentOS 7 (kmod-kvdo 6.1.3.23)?

**Comment by sweettea** [comment]
Greetings;

Unfortunately not possible at present. When the VDO is formatted, we record the version it was formatted with, and keep that format for the lifetime of the volume. This allows volumes made on 6.1 to work on 6.2, but unfortunately means that volumes using the slightly improved format on 6.2 are unknown to 6.1.

Many apologies.

**Comment by genxlee** [comment]
That is unfortunate taking into account last years CentOS project changes. Moving back to CentOS 7 would give few years thinking time to choose and test different options. I guess I am left with the time consuming solution - move data away from 6.2 VDO volume, re-create VDO volume with 6.1 format and move data back.
