### ISSUE TITLE
Kernel 4.17.14 and KVDO 6.1.0.181, failed build

### ISSUE THREAD

**Issue by serjponomarev** [dm-vdo/kvdo#13]
@corwin do you have variants to fix this issues?
_Centos 7.5, last kernel-ml and kernel-ml-devel from ELREPO_

```
make -C /usr/src/kernels/`uname -r` M=`pwd`
make: Entering directory `/usr/src/kernels/4.17.14-1.el7.elrepo.x86_64'
  AR      /home/kvdo-6.1.0.181/uds/built-in.a
  CC [M]  /home/kvdo-6.1.0.181/uds/stringLinuxKernel.o
  CC [M]  /home/kvdo-6.1.0.181/uds/threadSemaphoreLinuxKernel.o
/home/kvdo-6.1.0.181/uds/threadSemaphoreLinuxKernel.c: In function ‘acquireSemaphore’:
/home/kvdo-6.1.0.181/uds/threadSemaphoreLinuxKernel.c:99:7: error: implicit declaration of function ‘__set_task_state’ [-Werror=implicit-function-declaration]
       __set_task_state(task, TASK_INTERRUPTIBLE);
       ^
cc1: all warnings being treated as errors
make[2]: *** [/home/kvdo-6.1.0.181/uds/threadSemaphoreLinuxKernel.o] Error 1
make[1]: *** [/home/kvdo-6.1.0.181/uds] Error 2
make: *** [_module_/home/kvdo-6.1.0.181] Error 2
make: Leaving directory `/usr/src/kernels/4.17.14-1.el7.elrepo.x86_64'
```

**Comment by corwin** [comment]
I don't believe that the 6.1 versions of kvdo will work on a 4.17 kernel. Try the latest master version, 6.2.0.197, instead (note that you will also probably need to upgrade the user space tools (https://github.com/dm-vdo/vdo/releases/tag/6.2.0.197).

You may also be having another issue. Looking at the source file where you encountered the error, there is no call to __set_task_state(). This is probably the result of something in your build environment using the wrong include files for the kernel version you are building against. If switching to the 6.2.0.197 version of kvdo doesn't fix the problem, I would look into your environment next.

**Comment by serjponomarev** [comment]
@corwin from the main branch VDO & KVDO everything works fine, but Cockpit from the CentOS repository (version 169) does not understand the VDO management and does not work.
See the link below, last message
https://github.com/cockpit-project/cockpit/issues/8609

**Comment by corwin** [comment]
I'll have my team look into this.

**Comment by serjponomarev** [comment]
big thanks

**Comment by drckeefe** [comment]
I posted this in cockpit (https://github.com/cockpit-project/cockpit/issues/8609)
Newer version of VDO manager (6.2+) uses python 3. Centos 7.5 uses python 2. This might be the issue. Can you try using the 6.1 version of VDO manager with 6.2 version of kmod-kvdo on Centos 7.5 with the 4.17 kernel? I haven't tried it, but it might work for you.

serjponomarev followed up with this comment.

I already checked it.
Cockpit and VDO are working, the web console is also working.
The problem in the statistics, vdostats --si produces an error, VDOStatistics version mismatch
