### ISSUE TITLE
kvdo failed build on openSUSE Leap 42.3

### ISSUE THREAD

**Issue by serjponomarev** [dm-vdo/kvdo#6]
Get error when i try build **kvdo** (_vdo successful build_ ) on OpenSUSE 42.3 with last updates.

Kernel:
- kernel-default-4.4.114-42.1.x86_64
- kernel-devel-4.4.114-42.1.noarch
- kernel-source-4.4.114-42.1.noarch

```
make -C /usr/src/linux M=`pwd`
make: Entering directory '/usr/src/linux-4.4.114-42'

  WARNING: Symbol version dump ./Module.symvers
           is missing; modules will have no dependencies and modversions.

  CC [M]  /home/sw/dm-vdo/kvdo/uds/linuxIORegion.o
/home/sw/dm-vdo/kvdo/uds/linuxIORegion.c: In function ‘lior_bio_submit’:
/home/sw/dm-vdo/kvdo/uds/linuxIORegion.c:192:3: error: passing argument 1 of ‘submit_bio’ makes pointer from integer without a cast [-Werror]
   submit_bio(rw, bio);
   ^
In file included from /home/sw/dm-vdo/kvdo/uds/linuxIORegion.c:24:0:
include/linux/bio.h:411:17: note: expected ‘struct bio *’ but argument is of type ‘int’
 extern blk_qc_t submit_bio(struct bio *);
                 ^
/home/sw/dm-vdo/kvdo/uds/linuxIORegion.c:192:3: error: too many arguments to function ‘submit_bio’
   submit_bio(rw, bio);
   ^
In file included from /home/sw/dm-vdo/kvdo/uds/linuxIORegion.c:24:0:
include/linux/bio.h:411:17: note: declared here
 extern blk_qc_t submit_bio(struct bio *);
                 ^
cc1: all warnings being treated as errors
scripts/Makefile.build:270: recipe for target '/home/sw/dm-vdo/kvdo/uds/linuxIORegion.o' failed
make[2]: *** [/home/sw/dm-vdo/kvdo/uds/linuxIORegion.o] Error 1
scripts/Makefile.build:491: recipe for target '/home/sw/dm-vdo/kvdo/uds' failed
make[1]: *** [/home/sw/dm-vdo/kvdo/uds] Error 2
Makefile:1434: recipe for target '_module_/home/sw/dm-vdo/kvdo' failed
make: *** [_module_/home/sw/dm-vdo/kvdo] Error 2
make: Leaving directory '/usr/src/linux-4.4.114-42'
```

Please help to resolve this issue

**Comment by smarguet** [comment]
SuSE backports a lot into their kernel, like so: https://github.com/openSUSE/kernel-source/blob/openSUSE-42.3/patches.drivers/0175-block-rename-bio-bi_rw-to-bi_opf.patch

This confuses many of the LINUX_VERSION_CODE >= KERNEL_VERSION checks, particularly in bio.h, bio.c, dataKVIO.c and dmvdo.c.

You can work around it to build for SLE/OpenSuSE. I only got 2% savings on my datasets.

**Comment by corwin** [comment]
A similar issue was discussed on the vdo-devel list: https://www.redhat.com/archives/vdo-devel/2019-July/msg00002.html
