### ISSUE TITLE
compile fail with Ubuntu 18.04 (Kernel 4.15)

### ISSUE THREAD

**Issue by vampywiz17** [dm-vdo/kvdo#33]
Hello there,

I try to compile this module on ubuntu 18.04, but i get this error:

The headers is installed. Any ideas?

```
root@pure:~/kvdo# make -C /usr/src/linux-headers-`uname -r` M=`pwd`
make: Entering directory '/usr/src/linux-headers-4.15.0-106-generic'
  CC [M]  /root/kvdo/uds/openChapter.o
In file included from /root/kvdo/uds/indexLayout.h:28:0,
                 from /root/kvdo/uds/index.h:26,
                 from /root/kvdo/uds/openChapter.h:27,
                 from /root/kvdo/uds/openChapter.c:22:
/root/kvdo/uds/ioFactory.h:28:10: fatal error: linux/dm-bufio.h: No such file or directory
 #include <linux/dm-bufio.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.build:330: recipe for target '/root/kvdo/uds/openChapter.o' failed
make[2]: *** [/root/kvdo/uds/openChapter.o] Error 1
scripts/Makefile.build:604: recipe for target '/root/kvdo/uds' failed
make[1]: *** [/root/kvdo/uds] Error 2
Makefile:1577: recipe for target '_module_/root/kvdo' failed
make: *** [_module_/root/kvdo] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.0-106-generic'

```

**Comment by sweettea** [comment]
Hi vampywiz17;

What version of the code have you downloaded? If I recall correctly, kvdo 6.2+ requires a 4.18+ kernel; however, the kvdo 6.1 versions should work on kernel 4.15. If you haven't already, try the 6.1.3 branch -- https://github.com/dm-vdo/kvdo/tree/6.1.3 . Let me know if you have more problems!

**Comment by vampywiz17** [comment]
@sweettea 

Thanks it solve the kernel module problem!

But i try to compile it with same version "vdo" but i get python error (missing python utils )

so i install new kernel:

`sudo apt-get install --install-recommends linux-generic-hwe-18.04`

and the "master" branch (6.2.x.x) work withotut any problem!

**Comment by sweettea** [comment]
Excellent! Glad to hear you've had success :). Out of curiousity, how are you planning to use VDO, if you'd like to share? what kind of storage / filesystem / data type? I'm always interested to hear how people are using it.

**Comment by vampywiz17** [comment]
@sweettea 

Sure!

We will plan to backup vmware infrastructure, this software: https://pure.archiware.com/

The Virtual Appliance based on Ubuntu 18.04, it is the reason, that we not use Red hat or CentOS.

The storage is a Synology NAS that is connected to the Ubuntu VM via iSCSI protocol. I format the iSCSI based vdo disk to ext4.

it need to do a little tweak vdo systemd init script, i change the "`After`" field to "`open-iscsi.service`" It neccessary because normally it try to initalize, before the iSCSI connection is established (and of coure it cause a error)

It seems that do this job :)

![image](https://user-images.githubusercontent.com/14281430/92039213-02135780-ed75-11ea-91a1-b71b9549bc5e.png)

**Comment by vampywiz17** [comment]
It finished the full backup.

![image](https://user-images.githubusercontent.com/14281430/92081831-f8651080-edc3-11ea-8176-040317979b16.png)
