### PR TITLE
propagates some deprecation/changes for some kernel versions

### PR DESCRIPTION
**Pull request by potatogim**
There are some problems needed to fix that caused by some kernel version updates.

In my opinion, we need more fixes that are similar to this PR for more compatibility but I will need more tests :-) I tested it in FC 26 with Kernel 4.13

### CODE REVIEW

**Comment by xsuchy** [comment]
It is much better, but I am still getting:
```
/home/msuchy/projects/kvdo/uds/linuxIORegion.c: In function ‘lior_bio_init’:
/home/msuchy/projects/kvdo/uds/linuxIORegion.c:193:8: error: ‘struct bio’ has no member named ‘bi_bdev’; did you mean ‘bi_iter’?
   bio->bi_bdev = lior->bdev;
```

with kernel 4.14.13

**Comment by potatogim** [comment]
@xsuchy 

I have tried it with 4.13 but IMHO we need to support this version. I'm going to fix it from tomorrow! Thanks for your interesting!

**Comment by sweettea** [comment]
Hi @xsuchy @potatogim we have pending changes that support 4.13 and 4.14 -- they will be likely put here soon.

**Comment by potatogim** [comment]
@sweettea 

Do you mean  kvdo already has changes for that? If that is, I will close This PR :-)

**Comment by sweettea** [comment]
Not on github yet, but yes.

**Comment by potatogim** [comment]
Yes, I will close it.

**Comment by sweettea** [comment]
I'm sorry it took us 11 days to actually get it finished -- we turned out to have a problem with our per-thread storage mechanism that we needed to fix to actually run. We have just uploaded the newest version of VDO which ought to work on Fedora 27, either 4.13 or 4.14 kernels.
